### ISSUE TITLE
Select Diets

### ISSUE THREAD

**Issue by vamzzz** [ericyuegu/whaddya-havin#22]
Story: As a registered user I want to be able to view descriptions of various diet plans the app supports and the ability to set a diet plan to follow so I can track whether or not I am staying on the diet.

Scenario: A user wants to learn more about the various diets the app supports
Given: A user is on their profile page there is a drop-down menu or list with the various diets that the app supports.
When: The user clicks on one of the diets;
Then: A popup windows gives the user a brief description of the diet.

Scenario: A user want to set a diet to follow
Given: That the user is on the profile page there is a drop-down menu or list with the various diets that the app supports;
When: The user click on one of the diets;
Then: A popup window appears with a brief description of the diet and a toggle button allowing the user to set that diet as the one they are following.

Scenario: A user want to turn off following a diet
Given: That the user is on the profile page there is a drop-down menu or list with the various diets that the app supports;
When: The user click on one of the diets;
Then: A popup window appears with a brief description of the diet and a toggle button allowing the user to turn off following that diet.

**Comment by sunjayden** [comment]
Removed from Sprint 3 due to secondary features.
