### ISSUE TITLE
Registration Logic

### ISSUE THREAD

**Issue by vamzzz** [ericyuegu/whaddya-havin#5]
The registration logic should take an input:
• Full Name. A full name should include two parts: first and last name. Names should not include any numbers.
• Email Address. A valid email address is one that includes an "@" and a period afterwards in the most simplest version.
• Password. A valid password is one that is a minimum of 6 characters. This can be any combination of characters and/or special characters. For version 1, we are allowing users to create any password.

Passwords should have a confirmation of password to make sure the user knows the password they assigned for themselves. 

Proper implementation of the password will be encrypting the password in the database and not save in plain text.

**Comment by ericyuegu** [comment]
Completed as part of [commit d8086f0](https://github.com/ericyuegu/whaddya-havin/commit/d8086f0c13b62e3734c82c4507d34af256081f8f). TODO: Include full name as an input to be saved to Firebase DB.

**Comment by ericyuegu** [comment]
Follow-up issue:
https://github.com/ericyuegu/whaddya-havin/issues/11
