### ISSUE TITLE
User Interface of Logging In

### ISSUE THREAD

**Issue by vamzzz** [ericyuegu/whaddya-havin#6]
We are following Google Material Design to implement the user interface in the app. The UI will be made and then linked together with the backend logic.

**Comment by ericyuegu** [comment]
Completed as part of [commit d8086f0](https://github.com/ericyuegu/whaddya-havin/commit/d8086f0c13b62e3734c82c4507d34af256081f8f). TODO: https://github.com/ericyuegu/whaddya-havin/issues/12
